### PR TITLE
added hcloud-server target plugin

### LINKED ISSUE #465: Add implementation of Hetzner Cloud target plugin
Hi guys
Thank you for this amazing project, already using it for services scaling
My infrastructure is in both AWS and Hetzner datacenters. I'm already using Hetzner CSI plugin for Nomad, but unfortunately there's no scaling support yet.
It would be nice to add Hetzner Cloud servers support, cause it's very cheap and unfortunately there's no out of box scaling.

### PR DESCRIPTION
**Pull request by AndrewChubatiuk**
Fixes #465

### CODE REVIEW

**Comment by jrasell** [comment]
Hi @AndrewChubatiuk and thanks very much for this contribution. Internally later today the team will discuss the addition of this plugin and whether we believe it is better suited to being external such as the [Openstack Senlin](https://github.com/dkt26111/nomad-senlin-autoscaler) plugin or not. I will come back with more details later today once we have met.

Any review will likely take some time. The team doesn't have any experience with Hetzner and therefore will need to build infrastructure automation to test and verify the plugin; if we move forward with merging this into the core repo.

Thanks again.

**Comment by jrasell** [comment]
Hi @AndrewChubatiuk and thanks for your patience. Yesterday we discussed the question of additional target plugins and how we would continue. It was the conclusion, that at this current time we are unable to properly support additional target plugins, and therefore would like to have this live on as an external plugin. The overhead of supporting the additional code, as well as the testing infrastructure required is something we are unable to commit to. This does not mean this won't change in the future, and we are always happy to offer guidance as well as receive feedback around plugin development and integration.

We have [this page](https://www.nomadproject.io/docs/autoscaling/plugins/external) setup to start listing externally available plugins and would appreciate a PR raised to detail this plugin once it has a permanent location. There is also work in progress to make the current target plugin process clearer, alongside more general contribution information. I'll leave this PR open for another day, in case there are follow up comments.

Thanks again; jrasell and the Nomad team.

**Comment by AndrewChubatiuk** [comment]
Okay, got it. Thank you @jrasell 
@fhofherr @LKaemmerling
Is possible to add this plugin to hetznercloud organization?

**Comment by TheCrealm** [comment]
Is there any progress of releasing this as a plugin? I would really like to use this.

**Comment by AndrewChubatiuk** [comment]
@TheCrealm I can release it but I would like to add it to Hetzner organization

**Comment by LKaemmerling** [comment]
@AndrewChubatiuk 

Sorry for our late answer. We currently are not able to support this plugin. Therefore adding it to our organization does not makes sense. We would recommend that you release it under your account :)

**Comment by AndrewChubatiuk** [comment]
@TheCrealm @jrasell 
I've published a plugin and created a first release
https://github.com/AndrewChubatiuk/nomad-hcloud-autoscaler/releases/tag/v0.0.1

**Pull request closed without merging**
