### PR TITLE
Print autoscaler version to log on agent startup

### PR DESCRIPTION
**Pull request by baxor**
Figured it'd be nice to know which version produced which logfiles while debugging issues.  Change emits: 
```
➜ ./nomad-autoscaler agent
2021-01-12T12:35:59.415-0500 [INFO]  agent: nomad-autoscaler version v0.3.0-dev starting````

### CODE REVIEW

**Review by lgfa29 — APPROVED** [review]
Thanks for the PR @baxor, I think this is very valuable to have.

In the future we can improve this to have an output message closer to Nomad, maybe something like this:

```
==> No configuration files loaded
==> Starting Nomad Autoscaler agent...
==> Nomad Autoscaler agent configuration:

            Bind Addrs: HTTP: 127.0.0.1:8080
             Log Level: DEBUG
               Version: 0.2.0
               Plugins: ./bin/plugins
              Policies: ./policies

==> Nomad Autoscaler  agent started! Log data will stream in below:
...
``` 

But I don't think it's necessary now, unless you feel like adding it in this PR 😄 . Otherwise I will open an issue to expand this message.

We do need the CLA signed before merging it though. When you get a chance could you accept it? 

Thanks for the contribution!

**Comment by baxor** [comment]
Output is: 
```
➜ ./nomad-autoscaler agent --policy-dir=./foo --plugin-dir=./bar
2021-01-13T17:28:47.080-0500 [INFO]  agent: Starting nomad-autoscaler agent
2021-01-13T17:28:47.080-0500 [INFO]  agent: Nomad agent configuration:
2021-01-13T17:28:47.080-0500 [INFO]  agent:
2021-01-13T17:28:47.080-0500 [INFO]  agent:         Bind Addrs: 127.0.0.1
2021-01-13T17:28:47.080-0500 [INFO]  agent:          Log Level: info
2021-01-13T17:28:47.080-0500 [INFO]  agent:            Plugins: ./bar
2021-01-13T17:28:47.080-0500 [INFO]  agent:           Policies: ./foo
2021-01-13T17:28:47.080-0500 [INFO]  agent:            Version: v0.3.0-dev
2021-01-13T17:28:47.080-0500 [INFO]  agent:
2021-01-13T17:28:47.080-0500 [INFO]  agent: Nomad agent started! Log data will stream in below:
2021-01-13T17:28:47.080-0500 [INFO]  agent.http_server: server now listening for connections: address=127.0.0.1:8080
```

**Comment by baxor** [comment]
@lgfa29 done and done!

**Comment by baxor** [comment]
Oh, I skipped the `==> No configuration files loaded` bit as it seemed like it might take a bit of a rework of how and when policies are parsed.

**Comment by lgfa29** [comment]
Thank you for the changes and the contribution 😄

**Pull request merged**
