### PR TITLE
add max_scale_up and max_scale_down for pass-through

### PR DESCRIPTION
**Pull request by brmzkw**
This is similar to a4e70bcdba.

### CODE REVIEW

**Comment by brmzkw** [comment]
hey @lgfa29, do you think you can give a look to this PR?

**Comment by brmzkw** [comment]
up :)

**Review by lgfa29 — APPROVED** [review]
Hi @brmzkw, apologies for the delay here. Everything looks good, thanks for the PR!

Would you be able to add the new configuration values to the Nomad documentation as well?
https://github.com/hashicorp/nomad/blob/main/website/content/tools/autoscaling/plugins/strategy/pass-through.mdx

**Comment by brmzkw** [comment]
Great! thanks a lot!

Yes, I'll add the documentation too

**Pull request merged**
