### PR TITLE
Add OpenStack Senlin Cluster target plugin

### PR DESCRIPTION
**Pull request by dkt26111**
This adds a target plugin for OpenStack to scale Nomad cluster clients running as VMs in OpenStack using [Senlin](https://docs.openstack.org/senlin/latest/) clusters.

Senlin is the OpenStack service that allows users to create clusters of VMs for autoscaling purposes.  It is similar to AWS ASG.

### CODE REVIEW

**Comment by cgbaker** [comment]
Hi @dkt26111, thank you for the contribution. We're currently in the middle of a discussion about which plugins to include into this repo and which plugins to leave for external plugins. We will get back to you ASAP regarding a decision on this; if you have any opinion on that, we'd be glad to hear your perspective.

**Comment by dkt26111** [comment]
I have considered making this as an external plugin so I'm open to that.  Is there a clean way to use scaleutils.ScaleInReq with a custom RemoteProvider in an external plugin?  That seems to be the only blocker for me to make this an external plugin?

**Comment by cgbaker** [comment]
> Is there a clean way to use scaleutils.ScaleInReq with a custom RemoteProvider in an external plugin? That seems to be the only blocker for me to make this an external plugin.

well-noted, @dkt26111 . we had observed that ourselves and were in the process of addressing it. i'll post an issue to track that and list it here; this will be handled in the next release (0.3.0), along with a change to use gRPC for the plugin system.

**Comment by dkt26111** [comment]
Awesome, thanks.  Once that is available, I'll move this to an external plugin.

**Comment by jrasell** [comment]
Hi @dkt26111, the refactor is now available and has been released. If you come across any issues, or have any thoughts please let us know. :)

**Comment by dkt26111** [comment]
> Hi @dkt26111, the refactor is now available and has been released. If you come across any issues, or have any thoughts please let us know. :)

Thanks.  I will integrate the changes in the next couple days.

**Comment by dkt26111** [comment]
I tested my external plugin implementation with the nomad autoscaler 0.3.0 and verified that it works flawlessly.  Thank you for your help.  I will go ahead and close this PR.

For reference, the OpenStack Senlin target plugin is available here: https://github.com/dkt26111/nomad-senlin-autoscaler

**Comment by cgbaker** [comment]
hey @dkt26111 , great stuff! ❤️ 
we'll get this added to the list of community plugins as soon as we merge https://github.com/hashicorp/nomad/pull/10125

**Pull request closed without merging**
